### ISSUE TITLE
how to run main 

### ISSUE THREAD

**Issue by mahxn0** [yhmtsai/GPU-accelerated-Natural-Image-Stitching-with-Global-Similarity-Prior#1]
thank for your project 
 I had compiled it but i dont know how to run it  ? can you help me  thanks
![image](https://user-images.githubusercontent.com/19154155/31951314-4dd0fa02-b910-11e7-9692-a7bb6cc8b798.png)

**Comment by chiahoo2004** [comment]
Sorry for the late reply. The argument is the folder name containing target images under "input-42-data", not the path to each image. In your case, it's "./main APAP-train".

**Comment by mahxn0** [comment]
thank you！
